package pe.kabj.app_movil_kabj.model.enum

enum class Permission {

    MOBILE_HOME_VIEW,
    MOBILE_WORK_ORDER_REGISTER_VIEW,
    MOBILE_WORK_ORDER_CONSULT_VIEW,
    MOBILE_WORK_ORDER_ASSIGNED_LIST_VIEW,
    MOBILE_WORK_ORDER_LIST_VIEW,

    MOBILE_WORK_ORDER_CREATE,

    MOBILE_WORK_ORDER_SEARCH,
    MOBILE_WORK_ORDER_UPDATE,
    MOBILE_WORK_ORDER_DELETE,
    MOBILE_WORK_ORDER_CHANGE_STATE,

    MOBILE_WORK_ORDER_ASSIGN,
    MOBILE_FOREMAN_CONSULT,

    MOBILE_WORK_ORDER_ASSIGNED,
    MOBILE_WORK_ORDER_ASSIGNED_DETAIL

}